apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: orders 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orders 
    spec:
      containers:
        - name: orders 
          image: mmiprepo.azurecr.io/orders
          ports:
          - containerPort: 80
          livenessProbe:
            httpGet:
              path: /browser/index.html
              port: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "750m"
      imagePullSecrets:
        - name: mmiprepo-pullsecret
