apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: orders 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orders 
    spec:
      containers:
        - name: orders 
          image: mmiprepo.azurecr.io/orders
          ports:
          - containerPort: 80